import Head from 'next/head';
import React from 'react';
import { Banner } from '../components';

const Home = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="flex justify-center sm:px-4 p-12 pt-16">
      <div className="w-full minmd:w-4/5">
        <Banner childStyles="md:text-4xl sm:text-2xl xs:text-xl text-left" subtitle="- Local Marts Products" buttonLink="/products" name="We Offer the Best Products for everyone." parentStyles="justify-start mt-6 mb-6 h-72 sm:h-60 p-12 xs:p-4 xs:h-44 rounded-3xl" />
      </div>
    </div>
  </div>
);

export default Home;
