import Head from 'next/head';
import React, { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { useTheme } from 'next-themes';
import { Banner, Category, ProductCard } from '../components';
import images from '../assets';

const Home = () => {
  const [hideButtons, setHideButtons] = useState(false);
  const parentRef = useRef(null);
  const scrollRef = useRef(null);
  const { theme } = useTheme();

  const handleScroll = (direction) => {
    const { current } = scrollRef;

    const scrollAmount = window.innerWidth > 1800 ? 180 : 150;

    if (direction === 'left') {
      current.scrollLeft -= scrollAmount;
    } else {
      current.scrollLeft += scrollAmount;
    }
  };

  const isScrollable = () => {
    const { current } = scrollRef;
    const { current: parent } = parentRef;

    if (current?.scrollWidth >= parent?.offsetWidth) {
      setHideButtons(false);
    } else {
      setHideButtons(true);
    }
  };

  useEffect(() => {
    isScrollable();
    window.addEventListener('resize', isScrollable);

    return () => {
      window.removeEventListener('resize', isScrollable);
    };
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-center sm:px-4 p-12 pt-16">
        <div className="w-full minmd:w-4/5">
          <Banner childStyles="md:text-4xl sm:text-2xl xs:text-xl text-left" subtitle="- Local Marts Products" buttonLink="/products" name="We Offer the Best Products for everyone." parentStyles="justify-start mt-6 mb-6 h-72 sm:h-60 p-12 xs:p-4 xs:h-44 rounded-3xl" />
        </div>
        <div className="mt-2">
          <p className="text-subtitle-blue italic font-semibold text-base md:mb-4 sm:mb-1 ml-4 xs:ml-0">- The Categories</p>
          <h1 className="font-montserrat dark:text-white text-mart-black-1 text-3xl minlg:text-4xl xs:text-xl font-bold ml-4 xs:ml-0">Browse by Category</h1>
        </div>
        <div className="relative flex-1 max-w-full " ref={parentRef}>
          <div className="flex overflow-x-scroll no-scrollbar" ref={scrollRef}>
            <Category logo={images.logoDark} title="OnSale" />
            <Category logo={images.logoDark} title="Featured" />
            <Category logo={images.logoDark} title="Featured" />
            <Category logo={images.logoDark} title="Featured" />
            <Category logo={images.logo} title="Featured" />
            {/* <Category logo={images.logo} title="Featured" />
            <Category logo={images.logo} title="Featured" />
            <Category logo={images.logo} title="Featured" />
            <Category logo={images.logo} title="Featured" />
            <Category logo={images.logo} title="Featured" />
            <Category logo={images.logo} title="Featured" /> */}

            {!hideButtons && (
            <>
              <div className="absolute w-8 h-8 minlg:w-12 minlg:h-12 top-14 cursor-pointer -left-3">
                <Image onClick={() => { handleScroll('left'); }} src={images.leftArrow} layout="fill" objectFit="contain" alt="left-arrow" className={theme === 'dark' && 'filter invert'} />
              </div>
              <div className="absolute w-8 h-8 minlg:w-12 minlg:h-12 top-14 cursor-pointer -right-3">
                <Image onClick={() => { handleScroll('right'); }} src={images.rightArrow} layout="fill" objectFit="contain" alt="left-arrow" className={theme === 'dark' && 'filter invert'} />
              </div>
            </>
            )}

          </div>
          <div className="mt-2 flexBetween sm:flex-col sm:items-start">
            <div>
              <p className="text-subtitle-blue italic font-semibold text-base md:mb-4 sm:mb-1 ml-4 xs:ml-0">- Our Products</p>
              <h1 className="font-montserrat dark:text-white text-mart-black-1 text-3xl minlg:text-4xl xs:text-xl font-bold ml-4 xs:ml-0">Explore our Products</h1>
            </div>
            <div>SearchBar</div>
          </div>
          <div className="mt-3 w-full flex flex-wrap justify-start md:justify-center">
            {[1, 2, 3, 4, 5].map((i) => (
              <ProductCard
                key={`product-${i}`}
                product={{
                  i,
                  name: 'Demo Product 1',
                  price: 100,
                  image: 'https://i.ibb.co/2gsWw7b/Product.png',
                  discount: 50,
                  discountedPrice: 50,
                  category: 'Cloth',
                }}
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
export default Home;
