import React from 'react';
import Head from 'next/head';
import { Input } from '../components';

const Login = () => (
  <div>
    <Head>
      <title>Login</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="flex flex-col justify-end sm:px-4 p-12 pt-16">
      <div className="mt-8 flexBetween sm:flex-col sm:items-start">
        <div className="w-full">
          <p className="text-subtitle-blue italic font-semibold text-base md:mb-4 sm:mb-1 ml-4 xs:ml-0">- Login</p>
          <h1 className="font-montserrat dark:text-white text-mart-black-1 text-3xl minlg:text-4xl xs:text-xl font-bold ml-4 xs:ml-0">Login to Your Account</h1>
          <div className="m-auto w-2/5">
            <Input inputType="input" title="Email Address" placeholder="Enter your email" handleClick={() => {}} />
          </div>
        </div>
      </div>
    </div>
  </div>
);

export default Login;
