import React, { useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Input } from '../components';
import Button from '../components/Button';
import validateEmail from '../utils/validateEmail';

const validatePassword = (password) => (password.length >= 8);

const SignUp = () => {
  const router = useRouter();
  const [inputDetail, setInputDetail] = useState({ name: '', email: '', password: '' });
  const [validationMessage, setValidationMessage] = useState({ email: '', password: '' });

  const handleValidation = (attribute, value) => {
    if (attribute === 'email') {
      if (validateEmail(value)) {
        setValidationMessage({ ...validationMessage, email: '' });
      } else {
        setValidationMessage({ ...validationMessage, email: 'Enter a valid email' });
      }
    }

    if (attribute === 'password') {
      if (validatePassword(value)) {
        setValidationMessage({ ...validationMessage, password: '' });
      } else {
        setValidationMessage({ ...validationMessage, password: 'Password should have at least 8 characters.' });
      }
    }
  };

  return (
    <div>
      <Head>
        <title>SignUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-end sm:px-4 p-12 pt-16">
        <div className="mt-8 flexBetween sm:flex-col sm:items-start">
          <div className="w-full">
            <p className="text-subtitle-blue italic font-semibold text-base md:mb-4 sm:mb-1 ml-4 xs:ml-0">- Sign Up</p>
            <h1 className="font-montserrat dark:text-white text-mart-black-1 text-3xl minlg:text-4xl xs:text-xl font-bold ml-4 xs:ml-0">Create an account</h1>
            <div className="m-auto w-2/5 md:w-3/5 sm:w-4/5 xs:w-full">
              <Input inputType="input" title="Name" placeholder="Enter your name" handleClick={(e) => { setInputDetail({ ...inputDetail, name: e.target.value }); }} />
              <Input inputType="input" title="Email Address" placeholder="Enter your email" handleClick={(e) => { setInputDetail({ ...inputDetail, email: e.target.value }); handleValidation('email', e.target.value); }} />
              {validationMessage.email !== '' && <p className="absolute text-red-500">{validationMessage.email}</p>}
              <Input inputType="password" hidePassword title="Password" placeholder="Enter your password" handleClick={(e) => { setInputDetail({ ...inputDetail, password: e.target.value }); handleValidation('password', e.target.value); }} />
              {validationMessage.password !== '' && <p className="absolute text-red-500">{validationMessage.password}</p>}
              <div className="mt-12 w-full flex justify-between">
                <Button btnName="Create account" classStyles="rounded-md w-2/5 py-3 xs:py-2" />

                <Button btnName="Login" classStyles="rounded-md w-2/5 py-3 border text-black bg-gray-100 xs:py-2" handleClick={() => router.push('/login', undefined, { shallow: true })} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default SignUp;
